export const objLoadSave = {
  room: 0,
  north: 0,
  south: 0,
  east: 0,
  west: 0,
};
export const aryRooms = [
  {
    room: 0,
    north: 0,
    south: 0,
    east: 0,
    west: 0,
    win: false,
    lose: false,
    line1: "",
    line2: "",
    line3: "",
    line4: "",
    line5: "",
    line6: "",
    line7: "",
    line8: "",
    line9: "",
    line10: "",
    line11: "",
    line12: "",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "",
  },
  {
    room: 1,
    north: 0,
    south: 3,
    east: 0,
    west: 2,
    win: false,
    lose: false,
    line1:
      "It is a cold Monday morning. The rain beats heavily against the window, turning everything grey and miserable.",
    line2:
      "You stand by your desk, Windows 11 is chunterring to itself (as it does) and you know it will be at least 15 minutes",
    line3: "before its ready to be used.",
    line4: "",
    line5:
      "Now you know why SSDs where invented, if only you had one installed!",
    line6: "",
    line7:
      "The cheap metal table wobbles slightly under the vigour in which Windows 11 is mercilessly hammering the harddrive",
    line8: "simply because you switched on the computer.",
    line9: "",
    line10:
      "Romours of a new version of Windows coming, soon usual promises, higher specd machine required to use the same version",
    line11: "of Office as the last one...",
    line12: "",
    line13:
      "The bland magnolia walls of the office and the solitary strip light give an almost film noir feeling to the room.",
    line14:
      "Another huge pile of Windows issues awaits you today, more joys with printers Windows forgets exist, domain networks",
    line15:
      "suddenly becoming Public for no reason, shared network drives suddenly having incorrect credentials despite them being",
    line16: "correct...",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to your west, and another to the south",
  },
  {
    room: 2,
    north: 0,
    south: 0,
    east: 1,
    west: 0,
    win: false,
    lose: false,
    line1:
      "The room is small and dimly lit. There are shelves with computers on, and a rack of software.",
    line2: " ",
    line3:
      "Wow! You say out loud as you see a copy of Windows XP upgrade brand new and boxed. Those were the old days, networking",
    line4:
      "was easy and reliable, network shares didn't suddenly not work, mind you Internet Explorer was obsessed with giving  ",
    line5: "the computer viruses..",
    line6: "",
    line7:
      "There are all sorts of odd-bod software on the shelf, even Windows 3.11 for workgroups original floppies! ",
    line8: " ",
    line9: "",
    line10: " ",
    line11: " ",
    line12: "",
    line13: "   ",
    line14: "  ",
    line15: "  ",
    line16: " ",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to your east ",
  },
  {
    room: 3,
    north: 1,
    south: 4,
    east: 0,
    west: 0,
    win: false,
    lose: false,
    line1:
      "You find yousrself in a brightly lit corridor. The walls are dull magnolia and the carpet a happy beige, the corridor  ",
    line2: "is empty, it seems to stretch into infinity. ",
    line3: " ",
    line4:
      "The beigeness of it all seems strangely unsettling, there is a light humming noise like the sound inside a server room",
    line5:
      "there seemed to be a barely noticeable flicker to the ceiling lights.  ",
    line6: "",
    line7: "  ",
    line8: " ",
    line9: "",
    line10: "  ",
    line11: " ",
    line12: "",
    line13: "  ",
    line14: "  ",
    line15: "  ",
    line16: " ",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to your south and to the north",
  },
  {
    room: 4,
    north: 3,
    south: 6,
    east: 0,
    west: 5,
    win: false,
    lose: false,
    line1: "You find yousrself deeper in the brightly lit corridor.   ",
    line2: "The corridor is empty, it seems to stretch into infinity. ",
    line3: " ",
    line4:
      "The beigeness of it all seems strangely unsettling, there is a light humming noise like the sound inside a server room",
    line5:
      "there seemed to be a barely noticeable flicker to the ceiling lights.   ",
    line6: " ",
    line7:
      "Looking at the walls of corridor show a strange newness and blandness to the walls...  ",
    line8: "",
    line9: "  ",
    line10: " ",
    line11: "",
    line12: " ",
    line13: "  ",
    line14: "   ",
    line15: " ",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20:
      "There is a door to your west, and another to the south and to the north",
  },
  {
    room: 5,
    north: 0,
    south: 7,
    east: 4,
    west: 0,
    win: false,
    lose: false,
    line1:
      "You find yourself in a small room with and a desk with a lamp on it with a typewriter! ",
    line2: "",
    line3: "There is also a small window",
    line4: "",
    line5:
      "The walls are bare, the same blandess from the corridor seemed to somehow infect this small room.   ",
    line6:
      "Seems odd that no one is about, for a Monday that is weird, the window allows the dim sun light to come in from outside ",
    line7:
      "the faint hammering of the rain against the window acts like Musak giving a theme tune to your experience ",
    line8: "  ",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to your east, and another to the south",
  },
  {
    room: 7,
    north: 5,
    south: 0,
    east: 0,
    west: 8,
    win: false,
    lose: false,
    line1: "You find yourself in an even smaller room.  ",
    line2: "",
    line3:
      "In the corner of the room is an old beige server, it has an old 15 inch monitor on it. The monitor is on proudly",
    line4: "displaying the words: NT4 Server SP6a",
    line5: "",
    line6:
      "In the front of the server a DDS tape drive is whirring away to itself, the server has an old DIN connected Cherry",
    line7: "keyboard - no expense spared!",
    line8: "  ",
    line9:
      "Above the server is a small rack with an Allied Telesyn 24 port hub flashing away.",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to your north and to the west",
  },
  {
    room: 8,
    north: 0,
    south: 15,
    east: 7,
    west: 0,
    win: false,
    lose: false,
    line1: "The room is much bigger with two large desks with computers on it ",
    line2: "",
    line3:
      "You notice the first computer is on and the screen proudly displays a screensaver with Windows ME emblazened on it",
    line4: " ",
    line5:
      "The second computer is also on and that displays a screen with: Windows Vista on it",
    line6: " ",
    line7:
      "The Vista computer is chunterring to itself much like your Windows 11 computer, how far we have come!",
    line8: "  ",
    line9:
      "In the room the temperature does seem noticeable higher than normal, or was that just an illusion? ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the south and to the east",
  },
  {
    room: 15,
    north: 8,
    south: 16,
    east: 0,
    west: 0,
    win: false,
    lose: false,
    line1: "The lights in the room seem dimmer than the previous  ",
    line2: "",
    line3:
      "There is a small desk with a lamp it, the lamp is on and pointing to the keyboard on the desk",
    line4: "",
    line5:
      "It is illuminating the letters IBM, the computer desktop is stained beige, you see the words SX-33 on the case, in a ",
    line6: "nice comforting blue",
    line7: "",
    line8:
      "The screen is a beige 15 inch CRT (old skool!) on which it is a loading screen with: Windows 95 on it, a quick look",
    line9: "suggests it has crashed on loading, the room seems quite warm..",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north and the south",
  },
  {
    room: 16,
    north: 15,
    south: 0,
    east: 17,
    west: 0,
    win: false,
    lose: false,
    line1: "The room is darker than the previous  ",
    line2: "",
    line3:
      "There is a lonely looking old desk against one wall, there is a small window above it, which seems blocked",
    line4: " ",
    line5:
      "The desk has a computer on it with a very noisy fan, the tiny 14 inch monitor which boasts the words: EGA on it has a",
    line6: "screen on it that displays:",
    line7: "",
    line8: "    C:\\VER ",
    line9: " ",
    line10: "    MS-DOS Version 3.30",
    line11: "   ",
    line12: "    C:\\",
    line13: "",
    line14:
      "On the disk is a huge pile disks proudly labelled: Windows 3.11 for Workgroups, does seem awfully hot in here..",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north and to the east",
  },
  {
    room: 17,
    north: 18,
    south: 0,
    east: 0,
    west: 16,
    win: false,
    lose: false,
    line1:
      "The room is dark and hot, the light flicker strangely, there is an old oak table with a very old looking computer on it",
    line2: "",
    line3:
      "A 14 inch CRT green screen monitor, the screen is a bit fuzzy and has a strange bar that loops around the display.",
    line4: " ",
    line5: "On the display you can just about read:",
    line6: " ",
    line7: "   SCO XENIX SYSTEM V",
    line8: "  ",
    line9: "   Portions Copyright 1980-1989 Microsoft Corp.",
    line10: "   Portions Copyright 1983-1989 The Santa Cruz Oeration, Inc. ",
    line11: "   All rights reserved.",
    line12: " ",
    line13: "   XENIX is a registered trademark of Microsoft Corporation.",
    line14: "",
    line15: "   #",
    line16: "",
    line17: "A strange noise is coming from the room to the north....",
    line18: "",
    line19: "",
    line20: "There is a door to the north and the west",
  },
  {
    room: 18,
    north: 0,
    south: 0,
    east: 0,
    west: 0,
    win: false,
    lose: true,
    line1:
      "The room is large and brightly lit, the temperature is incredibly hot, you stagger into the room as the heat hits you  ",
    line2: "",
    line3:
      "You see a huge desk at one end of the room with a massive 30 inch monitor which proudly displays a message:   ",
    line4: " ",
    line5: "   Windows 12 is here!",
    line6: "    ",
    line7: "",
    line8: "      Upgrade now - or die!",
    line9: " ",
    line10: "      (ALL updates especially destructive updates are mandatory) ",
    line11: "   ",
    line12: " ",
    line13:
      "You hear a loud cackling behind you, spinning round you see Bill Gates grinning menacingly at you.",
    line14: "",
    line15:
      "Time to upgrade BOY! He shouts at you, he grabs your arm with impossible strength, the heat and brightness of the room",
    line16:
      "is draining your will to resist. A drill sounds somewhere near, with your vision blurring (it is sooooo hot!) you just",
    line17: "about see Gates other arm swing a drill at your left temple",
    line18: "",
    line19:
      "Need to fit a USB port Gates shouts with glee, you feel faint and lose consciousness...when you awake the room is now ",
    line20:
      "empty and over your vision is super-imposed: Windows 12 update installing please wait...   THE END",
  },
  {
    room: 6,
    north: 4,
    south: 9,
    east: 0,
    west: 0,
    win: false,
    lose: false,
    line1: "You find yousrself even deeper in the brightly lit corridor.   ",
    line2:
      "The corridor is empty, it seems to stretch into infinity just lie before. ",
    line3: " ",
    line4:
      "The beigeness of it all seems strangely unsettling, there is a light humming noise like the sound inside a server room",
    line5:
      "there seemed to be a barely noticeable flicker to the ceiling lights.   ",
    line6: " ",
    line7:
      "Looking at the walls of corridor show a strange newness and blandness to the walls...    ",
    line8: "",
    line9: "Who designed this?",
    line10: "",
    line11: "   ",
    line12: "",
    line13: "   ",
    line14: " ",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north and to the south",
  },
  {
    room: 9,
    north: 6,
    south: 0,
    east: 10,
    west: 0,
    win: false,
    lose: false,
    line1:
      "The corridor bends to the right, in the corner is a water dispenser with goldfish in it!  ",
    line2: "",
    line3:
      "There is a picture of Bill Gates on the wall holding a box with the words Windows 98SE on it, he seems happy..",
    line4: " ",
    line5:
      "On the floor is a single floppy disk, it has a label and on it is writen in large text:",
    line6: " ",
    line7: "  WINDOWS 2.0 PLUS GEM",
    line8: "  ",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north and the east",
  },
  {
    room: 10,
    north: 11,
    south: 0,
    east: 13,
    west: 9,
    win: false,
    lose: false,
    line1: "In the corridor is a small desk with flyers on it ",
    line2: "",
    line3:
      "Old adverts for Windows 1.0 and DOS as well as a barely visible flyer with: OS/2 Warp written on it",
    line4: " ",
    line5: "Strange there is no one here, wonder where all the employees are?",
    line6: " ",
    line7: "",
    line8: "  ",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north, the west and the east",
  },
  {
    room: 11,
    north: 0,
    south: 10,
    east: 12,
    west: 0,
    win: false,
    lose: false,
    line1:
      "The room is small and well lit, there is a small desk against the one wall, it has a small white-ish computer on it  ",
    line2:
      "you peer round to see the screen, the monitor has: Apple on it, the screen is displaying a program: Paint",
    line3: "  ",
    line4:
      "This room has lots of pictures on the wall, all with various old computers on them, there is a musty smell to the ",
    line5: "room and it reminds you of libraries",
    line6: " ",
    line7:
      "Seems cooler in here than the other rooms, you notice a wastepaper basket in the corner, in it is a magazine, you can",
    line8: "just about read the title: Linux Today",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the south and to the east",
  },
  {
    room: 12,
    north: 0,
    south: 13,
    east: 0,
    west: 11,
    win: false,
    lose: false,
    line1:
      "The room is large, with many desks on it, all with the monitors covered in a beige shroud ",
    line2: "",
    line3:
      "A loud hum fills the room, against one wall is a huge rack of rack mounted servers, next to it is a smaller rack with",
    line4: "racks of CDs on it",
    line5: "",
    line6:
      "You notice that none of the CDs are labelled, what is on them? What is on those servers? Why isn't the room air cooled ",
    line7: "with air conditioning?",
    line8: "  ",
    line9: "Many questions fill your head, but where to find the answers? ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the south and the west",
  },
  {
    room: 13,
    north: 12,
    south: 14,
    east: 0,
    west: 10,
    win: false,
    lose: false,
    line1:
      "This corridor never seems to end! Oh the blandness of it all...seems to drain the soul (bit like Windows updates)  ",
    line2: "",
    line3:
      "The magnolia walls seem to blend seamlessly into each other, almost as though it is some sort of rats maze where the  ",
    line4: "maze goes round in circles endlessly....",
    line5: "",
    line6: "You see a blue arrow on the wall pointing north ",
    line7: "",
    line8: "  ",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north, to the south and the west",
  },
  {
    room: 14,
    north: 13,
    south: 19,
    east: 0,
    west: 0,
    win: false,
    lose: false,
    line1: "The corridor seems brighter, no less draining and dreary..  ",
    line2: "",
    line3: "A voice sounds over some invisible public address system:  ",
    line4: " ",
    line5: "   Loyal employess, rejoice as Windows 12 is here!",
    line6:
      "   Please upgrade now...devops special systems, CEO and longhorn supporters exempt",
    line7: "  ",
    line8: "   Switch on, upgrade, update, update update!",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north and to the south",
  },
  {
    room: 19,
    north: 0,
    south: 14,
    east: 0,
    west: 20,
    win: false,
    lose: false,
    line1:
      "You enter a small room (sounds familiar), the beige carpet looks new there is a small desk in the corner with an award  ",
    line2: "on it:",
    line3: "  ",
    line4: " ",
    line5: "   Microsoft Award For Continuing Lack Of Development",
    line6: " ",
    line7: "   1998 - 2024",
    line8: "  ",
    line9: "   Goes To:",
    line10: "",
    line11: "   Windows Internet Security, Not Gone, Never Implemented",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the south and to the west",
  },
  {
    room: 20,
    north: 21,
    south: 0,
    east: 19,
    west: 22,
    win: false,
    lose: false,
    line1:
      "Seems a lot cooler in the corridor now, lights seem brighter, strange combination.. ",
    line2: "",
    line3:
      "The wall has a huge poster onto which is written in huge letters: XBOX 360  ",
    line4: " ",
    line5:
      "Wow! You think, that takes me back, at least it did not suffer from the red light of death like the PS3, maybe it is ",
    line6:
      "possible for Microsoft to make something that actually works and heck is even reliable?",
    line7: "",
    line8: "  ",
    line9: " ",
    line10: "",
    line11: "   ",
    line12: " ",
    line13: "",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the north, the east and to the west",
  },
  {
    room: 22,
    north: 0,
    south: 0,
    east: 20,
    west: 0,
    win: false,
    lose: false,
    line1:
      "You enter a small room, the lights are dim but you can see a small desk dimly lit with a failing lamp  ",
    line2: "",
    line3:
      "On the desk you can see an old Xbox 360 controller, an 80 pin SCSI drive and small notepad, with some writing on it,  ",
    line4: "you lean forward and just about read the words: ",
    line5: "",
    line6:
      "  Q: How many Microsoft engineers does it take to change a lightbulb?",
    line7: "",
    line8: "  A; NONE, they make darkness the industry standard ",
    line9: " ",
    line10: "",
    line11:
      "You see an old Commodore 64 in the corner, looking at the old machines reminds you of how it was instrumental in having   ",
    line12:
      "an interest in programming develop inside you, and how many happy hours your waited for tape games to load.. ",
    line13: "",
    line14:
      "Plus the joy of 6510 machine code, your mind is filled with an old image:",
    line15: "",
    line16: "   LDA #0",
    line17: "   STA $D020",
    line18: "   RTS",
    line19: "",
    line20: "There is a door to the east",
  },
  {
    room: 21,
    north: 0,
    south: 20,
    east: 0,
    west: 23,
    win: false,
    lose: false,
    line1:
      "There is a lively air to the room, the room is filled with racks of awards, you look at them, strangely the awards have  ",
    line2: "have white labels over any writing, why?",
    line3: "  ",
    line4:
      "Each corner of the room has a small table with a lamp on it, the lamps are on and the desks all have computers on them ",
    line5:
      "the screens are off and a white tape with bright red writing is wrapped around each computer",
    line6: " ",
    line7: "The tape says: TOP SECRET",
    line8: "  ",
    line9:
      "On the floor is a book (why is it on the floor?) the front of the book says: ",
    line10: "",
    line11: "   The Road Ahead",
    line12: " ",
    line13: "     Bill Gates",
    line14: "",
    line15: "",
    line16: "",
    line17: "",
    line18: "",
    line19: "",
    line20: "There is a door to the south, and the west",
  },
  {
    room: 23,
    north: 0,
    south: 0,
    east: 0,
    west: 0,
    win: true,
    lose: false,
    line1:
      "The room is large and at the one end is a huge open patio door, you see a long desk along on wall, it is full of books",
    line2: "and disks",
    line3: "",
    line4: "All the books and disks have the same word on them: LINUX",
    line5: "",
    line6:
      "Linux! You shout of course! No more chunterring, no more having the domain network randomly change to public so all",
    line7: "network shares fail, no more piles of driver disks",
    line8: "",
    line9:
      "Wow! The Linux printer driver offers a HUGE range of options the Windows does not, you get giddy with the excitement of",
    line10: "it all",
    line11: "",
    line12:
      "Windows, you remember needs insane system requirements just to run the SAME version of Office on your previous version",
    line13:
      "of Windows, no more sudden slow downs, dodgy updates, mandatory updates... ",
    line14: "",
    line15:
      "Farewell poor Service Packs we knew them well and how we miss them!",
    line16: "",
    line17:
      "That is it, you shout, Linux could not only save increase our workload and massively increase efficiency, but could alos",
    line18: "usher in a new era of world peace!",
    line19: "",
    line20:
      "Without a pause you grab as many Linux CDs as you can and flee out of the patio doors - THE END",
  },
];
